### ISSUE TITLE
Problème Maxsize dans oeuvre limité à 2048k

### ISSUE THREAD

**Issue by pascal-jego** [WildCodeSchool/bleau_S2_2016_corinne_creation#59]
J'ai modifié validation.yml à 4M
CorinneBundle\Entity\Objet:
    properties:
        source:
            - Image:
                maxSize: 4M
                mimeTypesMessage: Please charge une image valide

J'ai également modifié dans Entity/Objet.php 

 /**
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank(message="Please, upload the product brochure as a PDF file.")
     * @Assert\File(
     *     maxSize
     *      = "3048k",
     *     mimeTypes={ "image/jpeg", "image/jpg", "image/png" })
     */
    private $source;

Malgré cela cela reste bloqué à 2048k

**Comment by florianpdf** [comment]
J'ai fixé le bug, cela provenait de la configuration de php directement sur le serveur.
