### ISSUE TITLE
Probleme affichage image event

### ISSUE THREAD

**Issue by pascal-jego** [WildCodeSchool/bleau_S2_2016_corinne_creation#60]
Le champ source ne contient pas de données cohérentes ( /tmp/phpiSRLx9 )
Le répertoire web/uploads/img-event ne contient pas de fichier image

**Comment by juliengrima** [comment]
problème de compatibilité avec Firefox du calendrier fin de date .. correction dès que possible 
tout fonctionne sous chrome
